#! /bin/bash

set -o allexport; source .env; set +o allexport;

API_ENDPOINT=$REACT_APP_API_ENDPOINT
AUTH_DOMAIN=$REACT_APP_AUTH_DOMAIN
AUTH_CLIENT_ID=$REACT_APP_AUTH_CLIENT_ID
AUTH_CALLBACK_URL=$REACT_APP_AUTH_CALLBACK_URL
AUTH_LOGOUT_RETURN_URL=$REACT_APP_AUTH_LOGOUT_RETURN_URL
PERSIST_ENCRYPT_KEY=$REACT_APP_PERSIST_ENCRYPT_KEY

cat << EOM | kubectl patch -f config.yaml -p '
data:
  config.js: |-
    window.env = {
      API_ENDPOINT: "'$API_ENDPOINT'",
      AUTH_DOMAIN: "'$AUTH_DOMAIN'",
      AUTH_CLIENT_ID: "'$AUTH_CLIENT_ID'",
      AUTH_CALLBACK_URL: "'$AUTH_CALLBACK_URL'",
      AUTH_LOGOUT_RETURN_URL: "'$AUTH_LOGOUT_RETURN_URL'",
      PERSIST_ENCRYPT_KEY: "'$PERSIST_ENCRYPT_KEY'"
    }
'
EOM
